stages:
  - linting
  - test

ruff:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff --format=gitlab .
  allow_failure: true # TODO remove this

pytest:
  stage: test
  image: python:3.11
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate
  script:
    - pytest -v --cov=src --cov-report xml --cov-report term
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
