version: "3"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "alembic upgrade head && uvicorn src.identity.api.main:app --host 0.0.0.0 --port 8000 --reload"
    command: bash -c "uvicorn src.identity.api.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
    environment:
      - JWT_SECRET_KEY=1ed967dd1400b6de6b327342386fd01e14e63a4a45e4784e5248db7972097f54
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DB_USER=pablo
      - DB_PASSWORD=1234
      - DB_DATABASE=identity
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=pablo
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=identity
    ports:
      - "54321:5432"